[tool.poetry]
name = "lango"
version = "0.1.0"
description = "A framwork for LLM Applications. Inspired by Django, Laravel, and Meltano."
authors = ["Jacob Silva <jacob.silva@regulated.cloud>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
